import { Router } from 'express';
import activitiesRoutes from './activities.route';
import checkoutRoutes from './checkout.route';
import devicesRoutes from './devices.route';
import homeRoutes from './home.route';
import healthRoutes from './health.route';
import hotelsRoutes from './hotels.route';
import inventoryRoutes from './inventory.route';
import myTripsRoutes from './myTrips.route';
import notificationsRoutes from './notifications.route';
import ordersRoutes from './orders.route';
import paymentsRoutes from './payments.route';
import profileRoutes from './profile.route';
import providerDashboardRoutes from './providerDashboard.route';
import providerFinanceRoutes from './providerFinance.route';
import providerListingsRoutes from './providerListings.route';
import searchRoutes from './search.route';
import tripsRoutes from './trips.route';
import walletRoutes from './wallet.route';

const router = Router();

router.use('/activities', activitiesRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/devices', devicesRoutes);
router.use('/home', homeRoutes);
router.use('/health', healthRoutes);
router.use('/hotels', hotelsRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/my-trips', myTripsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/orders', ordersRoutes);
router.use('/payments', paymentsRoutes);
router.use('/profile', profileRoutes);
router.use('/provider/dashboard', providerDashboardRoutes);
router.use('/provider/finance', providerFinanceRoutes);
router.use('/provider/listings', providerListingsRoutes);
router.use('/search', searchRoutes);
router.use('/trips', tripsRoutes);
router.use('/wallet', walletRoutes);

export default router;
