import { Router } from 'express';
import adminRoutes from './admin.route';
import activitiesRoutes from './activities.route';
import authRoutes from './auth.route';
import chatRoutes from './chat.route';
import checkoutRoutes from './checkout.route';
import devicesRoutes from './devices.route';
import directMessagesRoutes from './directMessages.route';
import homeRoutes from './home.route';
import healthRoutes from './health.route';
import hotelsRoutes from './hotels.route';
import inventoryRoutes from './inventory.route';
import myTripsRoutes from './myTrips.route';
import notificationsRoutes from './notifications.route';
import ordersRoutes from './orders.route';
import paymentsRoutes from './payments.route';
import profileRoutes from './profile.route';
import providerDashboardRoutes from './providerDashboard.route';
import providerFinanceRoutes from './providerFinance.route';
import providerApplicationsRoutes from './providerApplications.route';
import providerListingsRoutes from './providerListings.route';
import providerVipRoutes from './providerVip.route';
import searchRoutes from './search.route';
import tripsRoutes from './trips.route';
import walletRoutes from './wallet.route';
import { requireAuth, requireRole } from '@/middlewares/auth';

const router = Router();

router.use('/admin', requireRole('ADMIN'), adminRoutes);
router.use('/activities', activitiesRoutes);
router.use('/auth', authRoutes);
router.use('/chat', requireAuth, chatRoutes);
router.use('/checkout', requireAuth, checkoutRoutes);
router.use('/devices', requireAuth, devicesRoutes);
router.use('/messages', requireAuth, directMessagesRoutes);
router.use('/home', homeRoutes);
router.use('/health', healthRoutes);
router.use('/hotels', hotelsRoutes);
router.use('/inventory', requireRole('PROVIDER'), inventoryRoutes);
router.use('/my-trips', requireAuth, myTripsRoutes);
router.use('/notifications', requireAuth, notificationsRoutes);
router.use('/orders', requireRole('PROVIDER'), ordersRoutes);
router.use('/payments', requireAuth, paymentsRoutes);
router.use('/profile', requireAuth, profileRoutes);
router.use('/provider-applications', requireAuth, providerApplicationsRoutes);
router.use('/provider/dashboard', requireRole('PROVIDER'), providerDashboardRoutes);
router.use('/provider/finance', requireRole('PROVIDER'), providerFinanceRoutes);
router.use('/provider/listings', requireRole('PROVIDER'), providerListingsRoutes);
router.use('/provider/vip', requireRole('PROVIDER'), providerVipRoutes);
router.use('/search', searchRoutes);
router.use('/trips', requireAuth, tripsRoutes);
router.use('/wallet', requireAuth, walletRoutes);

export default router;
