import { Router } from 'express';
import activitiesRoutes from './activities.route';
import authRoutes from './auth.route';
import checkoutRoutes from './checkout.route';
import devicesRoutes from './devices.route';
import homeRoutes from './home.route';
import healthRoutes from './health.route';
import hotelsRoutes from './hotels.route';
import inventoryRoutes from './inventory.route';
import myTripsRoutes from './myTrips.route';
import notificationsRoutes from './notifications.route';
import ordersRoutes from './orders.route';
import paymentsRoutes from './payments.route';
import profileRoutes from './profile.route';
import providerDashboardRoutes from './providerDashboard.route';
import providerFinanceRoutes from './providerFinance.route';
import providerListingsRoutes from './providerListings.route';
import searchRoutes from './search.route';
import tripsRoutes from './trips.route';
import walletRoutes from './wallet.route';
import { requireAuth, requireRole } from '@/middlewares/auth';

const router = Router();

router.use('/activities', activitiesRoutes);
router.use('/auth', authRoutes);
router.use('/checkout', requireAuth, checkoutRoutes);
router.use('/devices', requireAuth, devicesRoutes);
router.use('/home', homeRoutes);
router.use('/health', healthRoutes);
router.use('/hotels', hotelsRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/my-trips', requireAuth, myTripsRoutes);
router.use('/notifications', requireAuth, notificationsRoutes);
router.use('/orders', ordersRoutes);
router.use('/payments', requireAuth, paymentsRoutes);
router.use('/profile', requireAuth, profileRoutes);
router.use('/provider/dashboard', requireRole('PROVIDER'), providerDashboardRoutes);
router.use('/provider/finance', requireRole('PROVIDER'), providerFinanceRoutes);
router.use('/provider/listings', requireRole('PROVIDER'), providerListingsRoutes);
router.use('/search', searchRoutes);
router.use('/trips', requireAuth, tripsRoutes);
router.use('/wallet', requireAuth, walletRoutes);

export default router;
